#ifndef VITERBI_COMMON_H
#define VITERBI_COMMON_H

enum extr_trans_id
{
  EXTR_TRANS_RR,

  EXTR_TRANS_SN,
  EXTR_TRANS_NN,
  EXTR_TRANS_SB,
  EXTR_TRANS_NB,
  EXTR_TRANS_EB,
  EXTR_TRANS_JB,
  EXTR_TRANS_EJ,
  EXTR_TRANS_JJ,
  EXTR_TRANS_EC,
  EXTR_TRANS_CC,
  EXTR_TRANS_ET,
  EXTR_TRANS_CT,
};

enum core_trans_id
{
  CORE_TRANS_BM,
  CORE_TRANS_MM,
  CORE_TRANS_MI,
  CORE_TRANS_MD,
  CORE_TRANS_IM,
  CORE_TRANS_II,
  CORE_TRANS_DM,
  CORE_TRANS_DD,
};

typedef int (*viterbi_code_fn)(int pos, int len, void *arg);

#define VITERBI_TABLE_SIZE 1364
#define VITERBI_TIME_FRAME 6

#define VITERBI_DEBUG 0

#endif
