#ifndef XLIMITS_H
#define XLIMITS_H

enum
{
  DCP_ABC_NAME_SIZE = 16,
  DCP_PROFILE_NAME_SIZE = 64,
  DCP_NPARTITIONS_MAX = 128,
  DCP_NTHREADS_MAX = 128,
  DCP_PATH_MAX = 512,
  DCP_ACCESSION_SIZE = 32,
  DCP_CORE_SIZE = 16384,
};

#endif
