repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v17.0.6"
    hooks:
      - id: clang-format
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
