version: "3.8"
services:
  sched:
    image: danilohorta/deciphon-sched
    restart: unless-stopped
    ports:
      - "1515:8080"
    environment:
      - DECIPHON_SCHED_ALLOW_ORIGINS
      - DECIPHON_SCHED_LOG_LEVEL
      - DECIPHON_SCHED_S3_URL
      - DECIPHON_SCHED_MQTT_HOST
      - DECIPHON_SCHED_MQTT_PORT
      - DECIPHON_SCHED_DATABASE_URL
    depends_on:
      - minio
      - mosquitto
      - presser
      - scanner
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080" ]
      interval: 10s
      timeout: 10s
      retries: 10
    command:
      [
        "deciphon-sched",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--log-level",
        "debug"
      ]
  presser:
    image: danilohorta/deciphonctl
    restart: unless-stopped
    build: control
    environment:
      - DECIPHONCTL_SCHED_URL
      - DECIPHONCTL_MQTT_HOST
      - DECIPHONCTL_MQTT_PORT
    command:
      [
        "deciphonctl",
        "presser",
        "run",
        "--log-level",
        "debug"
      ]
    depends_on:
      - mosquitto
  scanner:
    image: danilohorta/deciphonctl
    restart: unless-stopped
    build: control
    environment:
      - DECIPHONCTL_SCHED_URL
      - DECIPHONCTL_MQTT_HOST
      - DECIPHONCTL_MQTT_PORT
    depends_on:
      - mosquitto
    command:
      [
        "deciphonctl",
        "scanner",
        "run",
        "--log-level",
        "debug"
      ]
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:9000/minio/health/live"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    command: [ "server", "/data", "--console-address", ":9001" ]
  mosquitto:
    image: docker.io/library/eclipse-mosquitto
    ports:
      - "1883:1883"
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-E",
          "-i",
          "healthcheck",
          "-W",
          "3"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    command: [ "mosquitto", "-c", "/mosquitto-no-auth.conf" ]
