version: "3.8"
services:
  sched:
    image: sched
    build: sched
    ports:
      - "8000:8000"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - DECIPHON_SCHED_S3_URL=http://localhost:9000
      - DECIPHON_SCHED_MQTT_HOST=localhost
      - DECIPHON_SCHED_MQTT_PORT=1883
    depends_on:
      - minio
      - mosquitto
      - presser
      - scanner
    volumes:
      - type: bind
        source: sched
        target: /app
    command:
      [
        "uvicorn",
        "--factory",
        "deciphon_sched.main:create_app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--log-level",
        "trace"
      ]
  presser:
    image: presser
    build: control
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - DECIPHONCTL_SCHED_URL=http://localhost:8000
      - DECIPHONCTL_MQTT_HOST=localhost
      - DECIPHONCTL_MQTT_PORT=1883
    command: [ "python", "-m", "deciphonctl", "presser", "run" ]
    depends_on:
      - mosquitto
  scanner:
    image: scanner
    build: control
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - DECIPHONCTL_SCHED_URL=http://localhost:8000
      - DECIPHONCTL_MQTT_HOST=localhost
      - DECIPHONCTL_MQTT_PORT=1883
    depends_on:
      - mosquitto
    command: [ "python", "-m", "deciphonctl", "scanner", "run" ]
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
    command: [ "mosquitto", "-c", "/mosquitto-no-auth.conf" ]
