services:
  sched:
    image: danilohorta/deciphon-sched
    restart: unless-stopped
    ports: ["8000:8000"]
    environment:
      DECIPHON_SCHED_PORT: ${SCHED_PORT}
      DECIPHON_SCHED_ALLOW_ORIGINS: ${SCHED_ALLOW_ORIGINS}
      DECIPHON_SCHED_LOG_LEVEL: ${SCHED_LOG_LEVEL}
      DECIPHON_SCHED_HOST: "0.0.0.0"
      DECIPHON_SCHED_S3_URL: "http://s3:9000"
      DECIPHON_SCHED_MQTT_HOST: mqtt
      DECIPHON_SCHED_MQTT_PORT: 1883
      DECIPHON_SCHED_DATABASE_URL: "sqlite+pysqlite:///:memory:"
    depends_on:
      - s3
      - mqtt
      - presser
      - scanner
    command: ["deciphon-sched"]
  presser:
    image: danilohorta/deciphon-worker
    restart: unless-stopped
    depends_on:
      - mqtt
    command: ["presser", "http://sched:8000", "mqtt", "1883", "--log-level", "debug"]
  scanner:
    image: danilohorta/deciphon-worker
    restart: unless-stopped
    depends_on:
      - mqtt
    command: ["scanner", "http://sched:8000", "mqtt", "1883", "--log-level", "debug"]
  s3:
    image: quay.io/minio/minio
    restart: unless-stopped
    ports: ["9000:9000"]
    command: ["server", "/data"]
  mqtt:
    image: library/eclipse-mosquitto
    command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
