name: 🏗 GUI build

on:
  push:
    branches:
      - "**"
    paths:
      - gui/**
      - .github/workflows/build-gui.yml

defaults:
  run:
    working-directory: gui

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install .

      - name: Build with Nuitka (MacOS 13 AMD64)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: develop
          script-name: gui/Deciphon.py
          mode: app
          output_dir: gui/build-macos-amd64
        if: matrix.os == 'macos-13'

      - name: Build with Nuitka (MacOS 14 ARM64)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: develop
          script-name: gui/Deciphon.py
          mode: app
          output_dir: gui/build-macos-arm64
        if: matrix.os == 'macos-14'

      - name: Build with Nuitka (Linux AMD64)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: develop
          script-name: gui/Deciphon.py
          mode: onefile
          output_dir: gui/build-linux-amd64
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build-macos-amd64/*.exe
            build-macos-amd64/*.bin
            build-macos-amd64/*.app/**/*
            build-macos-arm64/*.exe
            build-macos-arm64/*.bin
            build-macos-arm64/*.app/**/*
            build-linux-amd64/*.exe
            build-linux-amd64/*.bin
            build-linux-amd64/*.app/**/*
          include-hidden-files: true
