name: Release deciphon-snap

on:
  push:
    paths:
      - deciphon-snap/**
      - .github/workflows/release-deciphon-snap.yml
    tags:
      - deciphon-snap-v*

defaults:
  run:
    working-directory: deciphon-snap

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          pipx install poetry
          poetry build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: deciphon-snap/dist
          skip-existing: true
