name: 📦 Worker release

on:
  push:
    tags:
      - worker-v*

defaults:
  run:
    working-directory: worker

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/deciphon-worker

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Deploy
        run: |
          uv sync --all-extras --dev
          uv build
          uv publish

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: worker/dist
          skip-existing: true
          verbose: true
