name: 📦 Worker release

on:
  push:
    tags:
      - worker-v*

defaults:
  run:
    working-directory: worker

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: pipx run build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
          packages-dir: worker/dist
          skip-existing: true
