name: Release snap

on:
  push:
    tags:
      - snap-v*

defaults:
  run:
    working-directory: snap

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          pipx install poetry
          poetry build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
          packages-dir: ${{defaults.run.working-directory}}/dist
          skip-existing: true
