name: 📦 Poster release

on:
  push:
    tags:
      - poster-v*

defaults:
  run:
    working-directory: poster

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/deciphon-poster
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: poster/dist
          skip-existing: true
          verbose: true
