name: 🧪 Python-core testing

on:
  push:
    branches:
      - "**"
    paths:
      - python-core/**
      - .github/workflows/test-python-core.yml

defaults:
  run:
    working-directory: python-core

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: setup openmp and autoconf
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp autoconf
          echo "C_INCLUDE_PATH=$(brew --prefix)/opt/libomp/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$(brew --prefix)/opt/libomp/lib"       >> $GITHUB_ENV

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
