name: Test compose

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run compose
        run: docker compose up -d
      - name: Sleep
        run: sleep 30
      - name: Show containers
        run: docker compose ps
      - name: Logs
        run: docker compose logs
      - name: Sleep
        run: sleep 30
      - name: Show containers
        run: docker compose ps
      - name: Logs
        run: docker compose logs
      - name: Sleep
        run: sleep 30
      - name: Show containers
        run: docker compose ps
      - name: Logs
        run: docker compose logs
      - name: Run tests
        run: ./tests/test-compose.sh
