name: 🧪 Compose testing

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run compose
        run: docker compose --env-file compose.cfg up -d
      - name: Run tests
        run: ./tests/test-compose.sh
