name: 🧪 Cli testing

on:
  push:
    branches:
      - "**"
    paths:
      - cli/**
      - .github/workflows/test-cli.yml

defaults:
  run:
    working-directory: cli

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
