name: Test sched

on:
  push:
    branches:
      - "**"
    paths:
      - sched/**
      - .github/workflows/test-sched.yml

defaults:
  run:
    working-directory: sched

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          pipx install poetry
          poetry install
          poetry run pytest
