name: 🧪 Control testing

on:
  push:
    branches:
      - "**"
    paths:
      - control/**
      - .github/workflows/test-control.yml

defaults:
  run:
    working-directory: control

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
