name: 🧪 Cli testing

on:
  push:
    branches:
      - "**"
    paths:
      - cli/**
      - .github/workflows/test-cli.yml

defaults:
  run:
    working-directory: cli

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        run: |
          uv sync --all-extras --dev
          uv run pytest
