name: 🧪 Worker testing

on:
  push:
    branches:
      - "**"
    paths:
      - worker/**
      - .github/workflows/test-worker.yml

defaults:
  run:
    working-directory: worker

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: setup openmp and autoconf
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp autoconf
          echo "C_INCLUDE_PATH=${C_INCLUDE_PATH}:$(brew --prefix)/opt/libomp/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=${LIBRARY_PATH}:$(brew --prefix)/opt/libomp/lib"         >> $GITHUB_ENV

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
