name: 🧪 Python-core testing

on:
  push:
    branches:
      - "**"
    paths:
      - python-core/**
      - .github/workflows/test-python-core.yml

defaults:
  run:
    working-directory: python-core

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
