name: 🧪 C-core testing

on:
  push:
    branches:
      - "**"
    paths:
      - c-core/**
      - .github/workflows/test-c-core.yml

defaults:
  run:
    working-directory: c-core

jobs:
  test:
    runs-on: ${{matrix.os}}
    env:
      PREFIX:         ${{github.workspace}}/deps
      C_INCLUDE_PATH: ${{github.workspace}}/deps/include
      LIBRARY_PATH:   ${{github.workspace}}/deps/lib
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: clone lite-pack
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/lite-pack.git lite-pack

      - name: build & install lite-pack
        run: cd lite-pack && make && make install

      - name: build & install lite-pack-io
        run: cd lite-pack/ext && make && make install

      - name: clone hmmer3
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/hmmer3.git hmmer3

      - name: build & install hmmer-reader
        run: cd hmmer3/hmmer-reader && make && make install

      - name: build & install h3result
        run: cd hmmer3/h3result && make && make install

      - name: build & install h3client
        run: cd hmmer3/h3client && make && make install

      - name: clone imm
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/imm.git imm

      - name: build & install imm
        run: cd imm && make && make install

      - name: make
        run: make

      - name: make check
        run: make check
