name: Test python-core

on:
  push:
    branches:
      - "**"
    paths:
      - python-core/**
      - .github/workflows/test-python-core.yml

defaults:
  run:
    working-directory: python-core

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - uses: actions/checkout@v3

      - name: Install libomp
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Run tests
        run: |
          pipx install poetry
          poetry install
          poetry run pytest
